# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "paypal-permissions"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Isaac Hall"]
  s.date = "2012-07-19"
  s.description = "Ruby implementation of the PayPal Permissions API."
  s.email = "isaac@isaachall.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/paypal/permissions.rb",
    "lib/paypal/permissions/fault_message.rb",
    "lib/paypal/permissions/oauth.rb",
    "lib/paypal/permissions/paypal.rb",
    "lib/paypal/permissions/version.rb",
    "paypal-permissions.gemspec",
    "spec/oauth_spec.rb",
    "spec/paypal_spec.rb",
    "spec/spec_helper.rb",
    "spec/vcr/cancel_permission.yml",
    "spec/vcr/cancel_permission_invalid.yml",
    "spec/vcr/get_access_token_valid.yml",
    "spec/vcr/lookup_permissions_multiple.yml",
    "spec/vcr/request_permissions_multiple.yml",
    "spec/vcr/request_permissions_single.yml"
  ]
  s.homepage = "http://github.com/isaachall/paypal-permissions"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby implementation of the PayPal Permissions API."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httpclient>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.8.3"])
    else
      s.add_dependency(%q<httpclient>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<httparty>, ["~> 0.8.3"])
    end
  else
    s.add_dependency(%q<httpclient>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<httparty>, ["~> 0.8.3"])
  end
end

